### PR TITLE
Detect syntax version from project files to support parsing newer Julia syntax

### LINKED ISSUE #60826: coverage jobs broken by labeled break
https://buildkite.com/julialang/julia-master-scheduled/builds/1420#019bf952-7215-4883-815d-45ec97a209f8
```

ERROR: LoadError: ParseError("parsing error in stdlib/Dates/src/parse.jl:300: Base.Meta.ParseError(\"ParseError:\\n# Error @ none:20:36\\n            let val = tryparsenext_base10(s, i, end_pos, 1)\\n                val === nothing && break error\\n#                                  └─────────┘ ── labeled `break` not supported in Julia version 1.13 < 1.14\", Base.JuliaSyntax.ParseError(Base.JuliaSyntax.SourceFile(\"\\nfunction Base.parse(::Type{DateTime}, s::AbstractString, df::typeof(ISODateTimeFormat))\\n    i, end_pos = firstindex(s), lastindex(s)\\n    i > end_pos && throw(ArgumentError(\\\"Cannot parse an empty string as a DateTime\\\"))\\n\\n    coefficient = 1\\n    local dy\\n    dm = dd = Int64(1)\\n    th = tm = ts = tms = Int64(0)\\n    @label error begin\\n        @label done begin\\n            # Optional sign\\n            let val = tryparsenext_sign(s, i, end_pos)\\n                if val !== nothing\\n                    coefficient, i = val\\n                end\\n            end\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1)\\n                val === nothing && break error\\n                dy, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != '-' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 2)\\n                val === nothing && break error\\n                dm, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != '-' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 2)\\n                val === nothing && break error\\n                dd, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != 'T' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 2)\\n                val === nothing && break error\\n                th, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != ':' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 2)\\n                val === nothing && break error\\n                tm, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != ':' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 2)\\n                val === nothing && break error\\n                ts, i = val\\n                i > end_pos && break done\\n            end\\n\\n            c, i = iterate(s, i)::Tuple{Char, Int}\\n            c != '.' && break error\\n            i > end_pos && break done\\n\\n            let val = tryparsenext_base10(s, i, end_pos, 1, 3)\\n                val === nothing && break error\\n                tms, j = val\\n                tms *= 10 ^ (3 - (j - i))\\n                j > end_pos \|\| break error\\n            end\\n        end\\n\\n        return DateTime(dy * coefficient, dm, dd, th, tm, ts, tms)\\n    end\\n    throw(ArgumentError(\\\"Invalid DateTime string\\\"))\\nend\\n\", 7271, \"none\", 1, [1, 2, 90, 135, 221, 222, 242, 255, 278, 312, 335, 361, 389, 444, 479, 520, 540, 556, 557, 617, 664, 692, 734, 750, 751, 802, 838, 876, 877, 940, 987, 1015, 1057, 1073, 1074, 1125, 1161, 1199, 1200, 1263, 1310, 1338, 1380, 1396, 1397, 1448, 1484, 1522, 1523, 1586, 1633, 1661, 1703, 1719, 1720, 1771, 1807, 1845, 1846, 1909, 1956, 1984, 2026, 2042, 2043, 2094, 2130, 2168, 2169, 2232, 2279, 2307, 2349, 2365, 2366, 2417, 2453, 2491, 2492, 2555, 2602, 2631, 2673, 2716, 2732, 2744, 2745, 2812, 2820, 2872, 2876]), Base.JuliaSyntax.Diagnostic[Base.JuliaSyntax.Diagnostic(7923, 7933, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(7994, 8003, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8097, 8107, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8136, 8145, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8246, 8256, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8317, 8326, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8420, 8430, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8459, 8468, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8569, 8579, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8640, 8649, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8743, 8753, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8782, 8791, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8892, 8902, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(8963, 8972, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9066, 9076, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9105, 9114, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9215, 9225, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9286, 9295, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9389, 9399, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9428, 9437, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9538, 9548, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9609, 9618, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9712, 9722, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9751, 9760, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9861, 9871, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\"), Base.JuliaSyntax.Diagnostic(9975, 9985, :error, \"labeled `break` not supported in Julia version 1.13 < 1.14\")], :none))")
--
Stacktrace:
[1] amend_coverage_from_src!(fc::CoverageTools.FileCoverage)
@ CoverageTools /private/var/tmp/agent-tempdirs/default-honeycrisp-XC9YQX9HH2.0/tmp/jl_VV0tXs/packages/CoverageTools/UhDjW/src/CoverageTools.jl:186
[2] amend_coverage_from_src!(coverage::Vector{Union{Nothing, Int64}}, srcname::String)
@ CoverageTools /private/var/tmp/agent-tempdirs/default-honeycrisp-XC9YQX9HH2.0/tmp/jl_VV0tXs/packages/CoverageTools/UhDjW/src/CoverageTools.jl:152
[3] top-level scope
@ /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-master-scheduled/.buildkite/pipelines/scheduled/coverage/upload_coverage.jl:209
[4] include(mod::Module, _path::String)
@ Base ./Base.jl:309
[5] exec_options(opts::Base.JLOptions)
@ Base ./client.jl:344
[6] _start()
@ Base ./client.jl:585
in expression starting at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-master-scheduled/.buildkite/pipelines/scheduled/coverage/upload_coverage.jl:208


```

cc. @Keno

### PR DESCRIPTION
**Pull request by IanButterworth**
## Add version-aware parsing using JuliaSyntax

This PR enables CoverageTools to parse Julia source code across different syntax versions by:

**Key Changes:**
- Added **JuliaSyntax** as a dependency for version-aware parsing
- Implemented `detect_syntax_version()` to automatically detect the appropriate Julia syntax version by:
  - Checking `Project.toml`/`JuliaProject.toml` for explicit `syntax.julia_version` entries
  - Using `Base.project_file_load_spec()` when available (Julia 1.14+)
  - Falling back to `VERSION` file for Julia's `base/` source tree
  - Defaulting to `v"1.14"` (JuliaSyntax maintains backwards compatibility)
- Modified `amend_coverage_from_src!()` to use `JuliaSyntax.parsestmt()` with the detected version parameter
- Added `has_embedded_errors()` helper to detect parse errors in ASTs with proper error reporting
- Updated test expectations for the new error message format

**Why This Matters:**
This allows CoverageTools running under Julia 1.11 (or any version) to correctly parse Julia 1.14+ source code containing new syntax features like labeled breaks. Since JuliaSyntax provides version-aware parsing independent of the running Julia version, coverage analysis now works seamlessly across version boundaries.

**Implementation Details:**
- Raises minimum Julia version to 1.10 (for compatibility with JuliaSyntax)
- Handles edge cases: comment-only files, EOF detection, infinite loop prevention
- Maintains error reporting for actual syntax errors while being lenient with version-specific features

Fixes JuliaLang/julia#60826

Developed with Claude

### CODE REVIEW

File: src/CoverageTools.jl [hunk 1]
```diff
@@ -139,6 +139,101 @@ function process_cov(filename, folder)
...
+        end
+
+        parent = dirname(dir)
+        if parent == dir  # reached root
+            break
+        end
+        dir = parent
+    end
+    # Default to the current running Julia version if we can't determine it
+    return VERSION
```
Comment (Keno) [inline src/CoverageTools.jl]: Should we default to latest supported? Generally we'll keep syntax working except for corner cases.

File: src/CoverageTools.jl [hunk 2]
```diff
@@ -139,6 +139,101 @@ function process_cov(filename, folder)
...
+                            catch e
+                                e isa ArgumentError || rethrow()
+                            end
+                        end
+                    end
+                    # Check for julia compat entry
+                    if haskey(project, "compat") && haskey(project["compat"], "julia")
+                        compat_str = project["compat"]["julia"]
+                        # Parse the compat string - extract the first version number
+                        m = match(r"(\d+)\.(\d+)", compat_str)
```
Comment (Keno) [inline src/CoverageTools.jl]: This is not a correct implementation of compat. I would say to either copy the correct parsing code, or just parse everything with 1.14 syntax for now and then once 1.14 is out use the above code from base.

Comment (IanButterworth) [reply src/CoverageTools.jl]: Did the latter
